Repository NvChad/NvChad, pull requests merged in 2021-08, with the labels that each got.

#275 Greatly improve terminal features! Persistent terminals
  lua/chadrc.lua
  lua/mappings.lua
  lua/pluginList.lua
  lua/plugins/bufferline.lua
  lua/plugins/telescope.lua
  lua/plugins/toggleterm.lua
  lua/telescope/_extensions/terms.lua
  lua/utils.lua
Labels: enhancement

#281 make cheatsheet enabled by default
  lua/chadrc.lua
  lua/default_config.lua
  lua/pluginList.lua
Labels: enhancement

#294 feat: Added option for italic_comments
  lua/chadrc.lua
  lua/default_config.lua
  lua/highlights.lua
Labels: enhancement

#304 fix Dashboard docs, fix default_config issue
  lua/chadrc.lua
  lua/default_config.lua
  lua/plugins/dashboard.lua
Labels: bug, documentation

#306 Improve statusline config & hotifx close_buffer issue
  lua/utils.lua
Labels: bug, enhancement

#398 Aquarium Theme
  lua/colors/themes/aquarium.lua
Labels: theme
